# Generated by Django 3.1.7 on 2021-04-13 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schemes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(choices=[('Public Sector Banks', (('Bank of Maharashtra', 'Bank of Maharashtra'), ('Bank of Baroda', 'Bank of Baroda'), ('Bank of India', 'Bank of India'), ('Canara Bank', 'Canara Bank'), ('Central Bank of India', 'Central Bank of India'), ('IDBI Bank', 'IDBI Bank'), ('Indian Bank', 'Indian Bank'), ('Indian Overseas Bank', 'Indian Overseas Bank'), ('Punjab National Bank', 'Punjab National Bank'), ('Punjab & Sind Bank', 'Punjab & Sind Bank'), ('State Bank of India', 'State Bank of India'), ('UCO Bank', 'UCO Bank'), ('Union Bank', 'Union Bank'))), ('Private Sector Banks', (('Axis Bank', 'Axis Bank'), ('Bandhan Bank', 'Bandhan Bank'), ('Catholic Syrian', 'Catholic Syrian'), ('City Union Bank', 'City Union Bank'), ('DCB Bank', 'DCB Bank'), ('Dhanlaxmi Bank', 'Dhanlaxmi Bank'), ('Federal Bank', 'Federal Bank'), ('HDFC Bank', 'HDFC Bank'), ('ICICI Bank', 'ICICI Bank'), ('IDFC First Bank', 'IDFC First Bank'), ('IndusInd Bank', 'IndusInd Bank'), ('J & K Bank', 'J & K Bank'), ('Karnataka Bank', 'Karnataka Bank'), ('Kotak Bank', 'Kotak Bank'), ('Karur Vysya Bank', 'Karur Vysya Bank'), ('RBL Bank', 'RBL Bank'), ('South Indian Bank', 'South Indian Bank'), ('Tamilnad Mercantile Bank', 'Tamilnad Mercantile Bank'), ('TNSC Bank', 'TNSC Bank'), ('Yes Bank', 'Yes Bank')))], max_length=100)),
                ('scheme', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SchemeRates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intrest_rate', models.FloatField()),
                ('time_span', models.CharField(choices=[('short', '1 to 5 Years'), ('medium', '5 to 15 Years'), ('long', '15 Years & above')], max_length=100)),
                ('scheme_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments.schemes')),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invested_amount', models.IntegerField()),
                ('timespan', models.IntegerField()),
                ('scheme_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments.schemes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
