# Generated by Django 3.1.7 on 2021-04-12 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0002_auto_20210412_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensedata',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='expensedata', to='auth.user'),
            preserve_default=False,
        ),
    ]
