# Generated by Django 3.2.4 on 2021-06-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensedata',
            name='time',
            field=models.DateField(),
        ),
    ]
