# Generated by Django 3.1.7 on 2021-03-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='field',
            field=models.CharField(choices=[('gender', 'Gender'), ('profession', 'Profession')], max_length=100),
        ),
    ]
