# Generated by Django 3.1.7 on 2021-03-08 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210308_1254'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
