# Generated by Django 3.1.7 on 2021-03-10 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schemes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(choices=[('', '')], max_length=100)),
                ('scheme', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SchemeRates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intrest_rate', models.IntegerField()),
                ('time_span', models.CharField(choices=[('short', '1 to 5 Years'), ('medium', '5 to 15 Years'), ('long', '15 Years & above')], max_length=100)),
                ('scheme_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments.schemes')),
            ],
        ),
    ]
